module.exports = Promise.resolve([
    "Alec Peters",
    "Alpha Kaba",
    "Andrew White III",
    "Antonio Blakeney",
    "Austin Nichols",
    "Caleb Swanigan",
    "Cameron Oliver",
    "Chance Comanche",
    "Charles Cooke",
    "Damyean Dotson",
    "Davon Reed",
    "De'Aaron Fox",
    "Dennis Smith Jr.",
    "Dennis Smith Jr.NC",
    "Deonte Burton",
    "Derrick White",
    "Devin Robinson",
    "Dillon Brooks",
    "D.J.Wilson",
    "Donovan Mitchell",
    "Dwayne Bacon",
    "Edmond Sumner",
    "Edrice Adebayo",
    "Eric Mika",
    "Frank Jackson",
    "Frank Mason III",
    "Frank Ntilikina",
    "Harry Giles",
    "Ike Anigbogu",
    "Isaac Humphries",
    "Isaiah Briscoe",
    "Isaiah Hartenstein",
    "Isaiah Hicks",
    "Ivan Rabb",
    "Jacob Wiley",
    "Jaron Blossomgame",
    "Jarrett Allen",
    "Jawun Evans",
    "Jayson Tatum",
    "Johnathan Motley",
    "John Collins",
    "Jonah Bolden",
    "Jonathan Isaac",
    "Jonathan Jeanne",
    "Jordan Bell",
    "Jordan Mathews",
    "Josh Hart",
    "Josh Jackson",
    "Justin Jackson",
    "Justin Patton",
    "Kadeem Allen",
    "Kennedy Meeks",
    "Kobi Simmons",
    "Kris Jenkins",
    "Kyle Kuzma",
    "Lauri Markkanen",
    "L.J.Peak",
    "Lonzo Ball",
    "Luke Fischer",
    "Luke Kennard",
    "Luke Kornet",
    "Malcolm Hill",
    "Malik Monk",
    "Marcus Keene",
    "Marcus Marshall",
    "Markelle Fultz",
    "Mathias Lessort",
    "Maurice Watson Jr.",
    "Melo Trimble",
    "Monte Morris",
    "Nigel Hayes",
    "Nigel Williams",
    "OG Anunoby",
    "Peter Jok",
    "PJ Dozier",
    "Player",
    "Rodions Kurucs",
    "Semi Ojeleye",
    "Sindarius Thornwell",
    "Sterling Brown",
    "Terrance Ferguson",
    "Thomas Bryant",
    "TJ Leaf",
    "Tony Bradley",
    "Tyler Dorsey",
    "Tyler Lydon",
    "Wesley Iwundu",
    "Zach Collins",
    "Zak Irvin"
]);