version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.4 # webtask's nodejs version
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: 
          name: Install dependencies
          command: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: 
          name: Set config_test.json with API keys
          command: echo "$CONFIG_TEST" > config_test.json
      - run:
          name: Run tests
          command: yarn test
