name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 8.9.4 # webtask's nodejs version
      - env:
          CONFIG_TEST: ${{ secrets.CONFIG_TEST }}
        run: |
          echo "$CONFIG_TEST" > config_test.json
          yarn
          yarn test
